library(cowplot)
pdf(file="SDMs.pdf",paper = "USr", onefile = F)
# par(mfrow=c(4,5))
test1 <- plot.prediction(SE.mpwp.df)
test2 <- plot.prediction(SE.mis19.df)
test3 <- plot.prediction(SE.lig.df)
test4 <- plot.prediction(SE.lgm.df)
test5 <- plot.enmtools.maxent(sirtalis.samples.SE.max)
p <- plot_grid(test1,test2,test3,test4,test5, align = "h", greedy = T)
ggsave("SDMs.pdf", p, width=11, height=8.5)
dev.off()


plot.prediction(E.mpwp.df)
plot.prediction(E.mis19.df)
plot.prediction(E.lig.df)
plot.prediction(E.lgm.df)
plot.enmtools.maxent(sirtalis.samples.E.max)

plot.prediction(C.mpwp.df)
plot.prediction(C.mis19.df)
plot.prediction(C.lig.df)
plot.prediction(C.lgm.df)
plot.enmtools.maxent(sirtalis.samples.C.max)

plot.prediction(W.mpwp.df)
plot.prediction(W.mis19.df)
plot.prediction(W.lig.df)
plot.prediction(W.lgm.df)
plot.enmtools.maxent(sirtalis.samples.W.max)
dev.off()